Smoke Test Build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,21 +7,20 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     # parameters:
-    #Add parameter here
-      # workflow_id:
-      #   type: string
-      # event:
-      #   type: string 
+    #   # Add parameter here
+    #   workflow_id:
+    #     type: string
+    #   event:
+    #     type: string 
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
             echo "Destroy environment:${CIRCLE_WORKFLOW_ID:O:7}"
-            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:O:7} --recursive
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:O:7}
-            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:O:7}
-          # aws cloudformation delete-stack --stack-name udapeople-${CIRCLE_WORKFLOW_ID:0:7}            
+            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:O:7}           
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -29,21 +28,26 @@ commands:
     #   # Add parameter here     
     steps:
       - run:
-          name: Revert migrations when successful only
+          name: Revert migrations
           when: on_fail
           command: |
-                curl --insecure -d "success" https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/migration_$\{CIRCLE_WORKFLOW_ID:0:7} -d '1'
-          
+            SUCCESS=$(curl --insecure https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/UdaPeople-${CIRCLE_WORKFLOW_ID:0:7} -d '1')
+            if [ ${SUCCESS} = "success" ];
+            then
+              cd ~/project/backend
+              npm install
+              npm run migrations:revert
+            fi
 
-            # # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            # SUCCESS = 1
-            # if(( $SUCCESS==1 )); 
-            # then
-            # #  cd ~/project/backend
-            # #  npm install
-            # #  Add revert code here. You can find this in the Getting Started section.
-            #   exit 1
-            # fi
+        #  # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+        #  SUCCESS = 1
+        #  if(( $SUCCESS==1 )); 
+        #  then
+        #  #  cd ~/project/backend
+        #  #  npm install
+        #  #  Add revert code here. You can find this in the Getting Started section.
+        #    exit 1
+        #  fi
 
            
 jobs:
@@ -78,7 +82,6 @@ jobs:
              cd backend
              npm install
              npm run build
-
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
@@ -135,6 +138,7 @@ jobs:
           command: |
             cd frontend
             npm install
+          # npm install oauth-sign@^0.9.0
             npm audit fix --audit-level=critical --force
       - slack/notify:
           event: pass    
@@ -161,7 +165,7 @@ jobs:
           command: |
             cd backend
             npm install
-            # npm install oauth-sign@^0.9.0
+          # npm install oauth-sign@^0.9.0
             npm audit fix --audit-level=critical --force         
   
   # notify:
@@ -201,33 +205,27 @@ jobs:
             --template-file .circleci/files/frontend.yml \
             --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7} \
             --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7} \
-            --tags project=udapeople
+            --tags project=udapeople 
              
 
       - run:
-          name: Add udapeople back-end ip to ansible inventory
+          name: Add back-end ip to ansible inventory
           command: |
             echo "[web]" > .circleci/ansible/inventory.txt
             BACKEND_IP=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:O:7}" \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text) 
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text)
             echo ${BACKEND_IP}
             curl --insecure -d "${BACKEND_IP}" https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/UdaPeople-${CIRCLE_WORKFLOW_ID:0:7}-BackendIP
-            
+       
             echo ${BACKEND_IP} >> .circleci/ansible/inventory.txt
-          # >> ~/project/.circleci/ansible/inventory.txt
-          # cat ~/project/.circleci/ansible/inventory.txt
 
       - persist_to_workspace:
-          root: .circleci/ansible
+          root: ~/
           paths:
-            - inventory.txt
+            - project/.circleci/ansible/inventory.txt
       - destroy-environment
-          # event: on_fail    
-      # - destroy-environment
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      #     event: on_fail
       # Here's where you will add some code to rollback on failure      
 
   configure-infrastructure:
@@ -254,33 +252,26 @@ jobs:
           command: |
             cd .circleci/ansible
             ls -al
-            ansible-playbook -i inventory.txt configure-server.yml
+            ansible-playbook -i /tmp/.circleci/ansible/inventory.txt .circleci/ansible/configure-server.yml
       - destroy-environment
-      # - destroy-environment
-      # Here's where you will add some code to rollback on failure
-      # - destroy-environment:
-      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      #     event: on_fail
-         
+      # Here's where you will add some code to rollback on failure         
+  
   run-migrations:
     docker:
       # Docker image here that supports NodeJS
       - image: circleci/node:13.8.0
+        user: root
     steps:
       # Checkout code from git
       - checkout
       - restore_cache:
           keys: [backend-build]
-      # - run:
-      #     name: Install dependencies
-      #     command: |
-      #       apt-get update
-      #       apt -y install awscli
       - run:
           name: Run migrations
           command: |
             cd backend
             sudo npm install -g npm
+            npm install
             npm run migrations > migrations_dump.txt
             cat migrations_dump.txt
       - run:
@@ -288,12 +279,9 @@ jobs:
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-                
-                curl --insecure -d "success" https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/migration_$\{CIRCLE_WORKFLOW_ID:0:7} -d '1'
-            else
-                curl --insecure -d "failure" https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/migration_$\{CIRCLE_WORKFLOW_ID:0:7} -d '1'
+                curl --insecure https://kvdb.io/KYhyB7HfeoeV1Y4BLM9nKN/migration_$\{CIRCLE_WORKFLOW_ID:0:7}  -d '1'
             fi
-      - destroy-environment          
+      - destroy-environment
 
  # Here's where you will add some code to rollback on failure      
           
@@ -331,14 +319,9 @@ jobs:
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+
       - destroy-environment
-      - revert-migrations    
-      # - destroy-environment
-      # - revert-migrations
-      #       workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      #       event: on_fail
-      # - revert-migrations:
-      #       workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations
 
       # Here's where you will add some code to rollback on failure      
 
@@ -354,7 +337,7 @@ jobs:
          fingerprints: ["ca:00:63:fc:93:29:2a:30:1b:b9:65:bc:75:1d:2b:d0"]
       # attach workspace
       - attach_workspace:
-          at: ~/ 
+          at: ~/   
       - run:
           name: Install dependencies
           command: |
@@ -364,7 +347,6 @@ jobs:
       - run:
           name: Deploy backend
           command: |
-            pwd
             cd backend
             
             touch .env
@@ -394,15 +376,18 @@ jobs:
             echo "Contents of the inventory.txt file is -------"
             cat inventory.txt
             ansible-playbook -i inventory.txt deploy-backend.yml
+
       - destroy-environment
       - revert-migrations
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
       # your code here
       # Here's where you will add some code to rollback on failure  
 
   smoke-test:
     docker:
-      - image: python:3.10-alpine3.16
+      # Lightweight Docker image
+      - image: python:3.10-alpine3.16 
     steps:
       - checkout
       - run:
@@ -414,13 +399,8 @@ jobs:
           name: Get backend url and Backend Smoke test
           command: |
             export BACKEND_IP=$(aws ec2 describe-instances \
-<<<<<<< HEAD
             --query "Reservations[*].Instances[*].[PublicIpAddress]" \
             --filters "Name=tag:Name,Values=backend-${CIRCLE_WOEKFLOW_ID:0:7}" \
-=======
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
->>>>>>> 004bcb573ddeab726911ed098d2d4f78473cdb89
             --output text)
             echo ${BACKEND_IP}
 
@@ -430,7 +410,7 @@ jobs:
             export API_URL="http://${BACKEND}:3030"
             echo "API_URL=${API_URL}"
 
-            echo "Sleeping for 1 minute"
+            echo "Sleepin for 1 minute"
             sleep 60
 
             if curl -v "${API_URL}/api/status" | grep "ok"
@@ -446,16 +426,19 @@ jobs:
 
             echo ${URL}
 
-            if curl -s ${URL} | grep "Welcome"
+            if curl -s ${URL} | grep "welcome"
             then
+              # Change this to 0 after the job fails
               return 0
             else
               return 1
             fi
+
       - destroy-environment
-      - revert-migrations  
-    #  - destroy-environment
-    #  - revert-migrations
+      - revert-migrations
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure  
+
 
 workflows:
   default:
